# Based on https://material-theme.com/docs/reference/color-palette/

[main]
background        = "#0F111A"
foreground        = "#8F93A2"
text              = "#4B526D"
active_background = "#1A1C25"
active_foreground = "#FFFFFF"
buttons           = "#191A21"
second_background = "#181A1F"
contrast          = "#090B10"
border            = "#171825" # pale_black
highlight         = "#1F2233"
second_highlight  = "#31353e"
notifications     = "#090B10"
accent            = "#84ffff"
excluded          = "#292D3E"
error             = "#ff5370"
warning           = "#dcac2c"

[general]
green     = "#C3E88D"
turquoise = "#80CBC4"
blue      = "#82AAFF"
cyan      = "#89DDFF"
yellow    = "#FFCB6B"
orange    = "#F78C6C"
vermilion = "#ff776a"
red       = "#F07178"
purple    = "#C792EA"
gray      = "#464B5D" 
white     = "#E2E2E2"
black     = "#090B10"

[additional]
moon_light     = "#aec8ff"
pale_turquoise = "#acddd9"
pale_green     = "#d8f0b5"
sand           = "#ffdd9f"
cantaloupe     = "#fab49f"
pale_black     = "#171825"

[difference]
added_background   = "#2a312b"
changed_background = "#20283c"
removed_background = "#311f28"
