# Based on https://material-theme.com/docs/reference/color-palette/

[main]
background           = "#0F111A"
foreground           = "#8F93A2"
text                 = "#4B526D"
selection_background = "#717CB480"
selection_foreground = "#FFFFFF"
buttons              = "#191A21"
second_background    = "#181A1F"
disabled             = "#464B5D"   #include comments
contrast             = "#090B10"
active               = "#1A1C25"
border               = "#0F111A"
highlight            = "#1F2233"
tree                 = "#717CB430"
notifications        = "#090B10"
accent               = "#84ffff"
excluded             = "#292D3E"

[common]
green     = "#C3E88D"
turquoise = "#80CBC4"
blue      = "#82AAFF"
cyan      = "#89DDFF"
yellow    = "#FFCB6B"
orange    = "#F78C6C"
red       = "#F07178"
pink      = "#FF9CAC"
purple    = "#C792EA"
magenta   = "#cc76e9"
gray      = "#717CB4"
white     = "#E2E2E2"
black     = "#090B10"

error     = "#ff5370"
warning   = "#dcac2c"

[additional]
moon_light     = "#aec8ff"
pale_turquoise = "#acddd9"
pale_green     = "#d8f0b5"
sand           = "#ffdd9f"
cantaloupe     = "#fab49f"
pale_black     = "#171825"

vermilion    = "#ff5a49"
trident_gold = "#ffcc00"

[toxic]
plum    = "#9b117b"
crimson = "#d10020"
